backend:
  name: github
  repo: romchikchan/music-library
  branch: main

# Для локальной разработки:
local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "songs"
    label: "Песни"
    folder: "src/content/songs"
    create: true
    slug: "{{slug}}"
    
    fields:
      - {label: "Название песни", name: "title", widget: "string"}
      - {label: "Исполнитель", name: "artist", widget: "string", required: false}
      
      - label: "Бас-гитара"
        name: "bass"
        widget: "object"
        fields:
          - {label: "Songsterr ссылка", name: "songsterr", widget: "string", required: false}
          - {label: "YouTube ссылка", name: "youtube", widget: "string", required: false}
          - {label: "Табы", name: "tabs", widget: "text", required: false}
      
      - label: "Гитара (ритм)"
        name: "guitar_rhythm"
        widget: "object"
        fields:
          - {label: "Songsterr ссылка", name: "songsterr", widget: "string", required: false}
          - {label: "YouTube ссылка", name: "youtube", widget: "string", required: false}
          
      - label: "Гитара (соло)"
        name: "guitar_solo"
        widget: "object"
        fields:
          - {label: "Songsterr ссылка", name: "songsterr", widget: "string", required: false}
          - {label: "YouTube ссылка", name: "youtube", widget: "string", required: false}
      
      - label: "Ударные"
        name: "drums"
        widget: "object"
        fields:
          - {label: "Songsterr ссылка", name: "songsterr", widget: "string", required: false}
          - {label: "YouTube ссылка", name: "youtube", widget: "string", required: false}
      
      - label: "Текст песни"
        name: "lyrics"
        widget: "markdown"
        required: false